apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-viewer-webapp
  labels:
    app: trip-viewer-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-viewer-webapp
  template:
    metadata:
      labels:
        app: trip-viewer-webapp
    spec:
      containers:
      - name: trip-viewer-webapp
        image: registryski3694.azurecr.io/tripinsights/tripviewer:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80